version: '3'
services:
  hw3helper_bot:
    image: hw3helper_bot_bot:latest
    environment:
      - TOKEN=${TOKEN}
      - STORAGE_NODE=hw3helper_bot_db:5000
    volumes:
      - storage:storage

  hw3helper_bot_db:
    image: hw3helper_bot_db:latest
    ports:
      - "5000:5000"
